apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 6
  selector:
    app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
        - name: myapp-pod-fc
          image: sasidevopss/myjavaimage24june2022
          ports:
            - containerPort: 8080
