apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  selector:
    app: myapp-pod
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myapp-pod
        version: 2.6.1
    spec:
      containers:
        - name: myapp-pod-fc
          image: sasidevopss/myjavaimage24june2022:1
          ports:
            - containerPort: 8080
