apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-nginx-rc
spec:
  replicas: 3
  selector:
    app: myapp-nginx
  template:
    metadata:
      name: myapp-nginx
      labels:
        app: myapp-nginx
    spec:
      containers:
        - name: myapp-nginx-fstcr
          image: nginx
          ports:
            - containerPort: 80
