apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  selector:
    app: myapp-pod
    version: 2.6.2
  template:
    metadata:
      labels:
        app: myapp-pod
        version: 2.6.2
    spec:
      containers:
        - name: myapp-pod-fc
          image: sasidevopss/myjenkinsimage05july2022:2
          ports:
            - containerPort: 8080
